In [107]:
import tensorflow as tf
import math
#L = 2, dim(key) = 3, dim(value) = 3, Lq = 2
L = 2
dim_key = 3
Lq = 2
diim_value = 3

K = tf.constant([[1.0, 2.0, 3.0],
                 [3.0, 20.0, 5.0]]) #L * dim(key), 
Q = tf.constant([[4.0, 2.0, 4.0], 
                 [4.0, 1.0, 10.0]]) #Lq * dim(key)
V = tf.constant([[2, 3, 4],
                 [4.0, 3.0, 8.0]]) #L * dim(value) 

C1 = tf.matmul(Q, K, transpose_b=True)   #Softmax should be dim(K) * dim(V), 这里K维代表的是每一个K的组合
C2 = tf.constant([[2, 7.2],
                [3.6, 8.2]])
C3 = tf.constant([[ 20/10,  72/10],
                  [ 36/10,  82/10]])

A1 = tf.nn.softmax(C1)
A3 = tf.nn.softmax(C3)

V= tf.cast(V, tf.float32)
KQV_a1 = tf.matmul(A1, V)
KQV_a3 = tf.matmul(A3, V)


In [108]:
with tf.Session() as sess:
    print ("QK' beftore scaled:")
    print (sess.run(C1))
    print ("Attention before scaled:")
    print (sess.run(A1))
    print ("The next Query before scaled:")
    print (sess.run(KQV_a1))
    
    print ("QK' after scaled by dk:")
    print (sess.run(C3))
    print ("Attention after scaled:")
    print (sess.run(A3))
    print ("The next Query after scaled:")
    print (sess.run(KQV_a3))

QK' beftore scaled:
[[ 20.  72.]
 [ 36.  82.]]
Attention before scaled:
[[  2.61027905e-23   1.00000000e+00]
 [  1.05306175e-20   1.00000000e+00]]
The next Query before scaled:
[[ 4.  3.  8.]
 [ 4.  3.  8.]]
QK' after scaled by dk:
[[ 2.          7.19999981]
 [ 3.5999999   8.19999981]]
Attention after scaled:
[[ 0.0054863   0.99451375]
 [ 0.0099518   0.99004817]]
The next Query after scaled:
[[ 3.9890275   3.00000024  7.978055  ]
 [ 3.98009634  3.          7.96019268]]


In [109]:
import tensorflow as tf
import numpy as np

input_ids = tf.placeholder(dtype=tf.int32, shape=[None])

embedding = tf.Variable(np.identity(5, dtype=np.int32))
input_embedding = tf.nn.embedding_lookup(embedding, input_ids)

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
print(embedding.eval())
print(sess.run(input_embedding, feed_dict={input_ids:[1, 2, 3, 0, 3, 2, 1]}))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]]
