In [18]:
import tensorflow as tf
test_data = tf.constant([[1.0], [2.0], [3.0]])
test_sm = tf.nn.softmax(test_data)
test_sm_T = tf.transpose(test_sm)
mat1 = tf.constant([[2.0, 20.0], [1.0, 10.0], [0.5, 5.0], [0.25, 2.5]])
mat1_softmax = tf.nn.softmax(mat1)

In [19]:
with tf.Session() as sess:
    print (sess.run(test_sm))
    print (sess.run(test_sm_T))
    print (sess.run(mat1_softmax))

[[ 1.]
 [ 1.]
 [ 1.]]
[[ 1.  1.  1.]]
[[  1.52299791e-08   1.00000000e+00]
 [  1.23394580e-04   9.99876618e-01]
 [  1.09869428e-02   9.89013076e-01]
 [  9.53494608e-02   9.04650509e-01]]
