In [14]:
import tensorflow as tf
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35))
W2 = tf.Variable(initial_value=tf.random_gamma([10], [0.5, 1.5]))
W3 = tf.Variable(initial_value=tf.linspace(start=10.0, stop=12.0, num=3))
a = tf.zeros([3, 4], tf.int32)
b = tf.zeros_like([[1, 2, 3], [4, 5, 6]])
c = tf.fill([2, 3], 9)
weights = tf.Variable(tf.random_normal(shape=(1, 4), stddev=0.35), name="weights")

In [17]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (sess.run(W))
    print (sess.run(W2))
    print (sess.run(W3))
    print (sess.run(a))
    print (sess.run(b))
    print (sess.run(c))
    print (sess.run(weights))
    print (tf.global_variables())

[[  99.80930328  100.02727509  100.22644043   99.55309296]]
[[  4.99328405e-01   1.48124886e+00]
 [  4.23995256e-01   1.23796129e+00]
 [  3.01675290e-01   4.58564848e-01]
 [  9.94044617e-02   3.99283558e-01]
 [  2.87610926e-02   5.47406137e-01]
 [  5.31611554e-02   5.14783859e-01]
 [  1.07742810e+00   4.96799916e-01]
 [  7.81522412e-03   1.31598246e+00]
 [  1.56601250e+00   5.06877184e-01]
 [  1.34150311e-03   8.83785307e-01]]
[ 10.  11.  12.]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0]
 [0 0 0]]
[[9 9 9]
 [9 9 9]]
[[-0.0362974  -0.24355324 -0.01400177  0.3343108 ]]
[<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32_ref>, <tf.Variable 'Variable_1:0' shape=(1, 4) dtype=float32_ref>, <tf.Variable 'Variable_2:0' shape=(10, 2) dtype=float32_ref>, <tf.Variable 'Variable_3:0' shape=(1, 4) dtype=float32_ref>, <tf.Variable 'Variable_4:0' shape=(10, 2) dtype=float32_ref>, <tf.Variable 'Variable_5:0' shape=(1, 4) dtype=float32_ref>, <tf.Variable 'Variable_6:0' shape=(10, 2) dtype=float32_ref>,