In [22]:
import tensorflow as tf
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v", [2, 4], initializer=tf.zeros_initializer())
    
g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("v", [1, 4], initializer=tf.ones_initializer())
    
g3 = tf.Graph()
with g3.as_default():
    value = [[2, 4, 6], [4, 6, 8]]
    init = tf.constant_initializer(value)
    v = tf.get_variable("v", [2, 3], initializer=init)
    
#Step1: Define the value
#Step2: Define the initializer
#Step3: Initialize the variable


In [23]:
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v")))

with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v")))
        
with tf.Session(graph=g3) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v")))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]]
[[ 2.  4.  6.]
 [ 4.  6.  8.]]
