In [32]:
import tensorflow as tf
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v", [2, 4], initializer=tf.zeros_initializer())
    
g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("v", [1, 4], initializer=tf.ones_initializer())
    
g3 = tf.Graph()
with g3.as_default():
    value = [[2, 4, 6], [4, 6, 8]]
    init = tf.constant_initializer(value)
    v = tf.get_variable("v", [2, 3], initializer=init)
    
#Step1: Define the value
#Step2: Define the initializer
#Step3: Initialize the variable

g4 = tf.Graph()
with g4.as_default():
    value = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
    init = tf.constant_initializer(value)
    value2 = [[4, 4, 4], [5, 5, 5], [6, 6, 6]]
    v4 = tf.get_variable("v4", [3, 3], initializer=init)
    init2 = tf.constant_initializer(value2)
    v5 = tf.get_variable("v5", [4, 3], initializer=init2)


In [33]:
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v")))

with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v")))
        
with tf.Session(graph=g3) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v")))
        
with tf.Session(graph=g4) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print (sess.run(tf.get_variable("v4")))
        print (sess.run(tf.get_variable("v5")))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]]
[[ 2.  4.  6.]
 [ 4.  6.  8.]]
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
[[ 4.  4.  4.]
 [ 5.  5.  5.]
 [ 6.  6.  6.]
 [ 6.  6.  6.]]
